<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 19 Mar 2011 14:04:53 -0400
 */

$conf['title'] = 'default';
$conf['start'] = 'index';
$conf['template'] = 'minimal';
$conf['license'] = 'publicdomain';
$conf['youarehere'] = 1;
$conf['maxseclevel'] = '0';
$conf['deaccent'] = '2';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['tpl']['minimal']['footer-text'] = 'a <a href="http://www.headstrong.de">headstrong</a> venture';
$conf['removeips'] = '1';

// end auto-generated content
