<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: test
 * Date: Sat, 19 Mar 2011 04:47:07 -0400
 */

$conf['title'] = 'default';
$conf['template'] = 'dokuwiki-minimal';
$conf['license'] = 'publicdomain';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';

// end auto-generated content
