<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 19 Mar 2011 07:07:55 -0400
 */

$conf['title'] = 'default';
$conf['template'] = 'minimal';
$conf['license'] = 'publicdomain';
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['tpl']['minimal']['hide-entry-title'] = 1;
$conf['tpl']['minimal']['footer-text'] = 'a <a href="http://www.headstrong.de">headstrong</a> venture';

// end auto-generated content
